### ISSUE TITLE
source directory is missing.

### ISSUE THREAD

**Issue by arden** [LoganWright/Genome#11]
source directory is missing.

**Comment by LoganWright** [comment]
Hi @arden 

The source files are actually in the playground's sources folder.  I mentioned this in the readme, but I just noticed the link is broken.  You can find the files here:

https://github.com/LoganWright/Genome/tree/master/Genome.playground/Sources

This is because I wanted to provide a playground to play with the library, but I didn't want to maintain two sets of files.  The files in Xcode are referenced to the playground's directory.

**Comment by LoganWright** [comment]
Just updated, thanks for checking out the library.  Let me know if you have any other issues!

Best,

Logan
