### ISSUE TITLE
Core Data documentation

### ISSUE THREAD

**Issue by SPopenko** [LoganWright/Genome#2]
Hi guys, your framework look promising and very clear! I would like to ask extend Core data support documentation. Especially what I'm interesting in is: how to get some keys from JSON in init section to link with existing objects in CD and not to create new one?

**Comment by LoganWright** [comment]
Hi @SPopenko 

Thanks for the suggestion, I'll leave this open until I get a chance to update the README.

For now, here's what you should override:

```ObjC
+ (instancetype)gm_newInstanceForJsonRepresentation:(NSDictionary *)jsonRepresentation;
```

When a new object is mapped, this method is called first to receive an instance for mapping.  If it is not overridden, it ultimately just calls `alloc] init];`.  You could do something like this in your class

```Objc
@implementation MyCoreDataClass 

+ (instancetype)gm_newInstanceForJsonRepresentation:(NSDictionary *)jsonRepresentation {
    NSString *identifier = jsonRepresentation[@"identifier"];
    id object = [MyCoreDataManager objectWithIdentifier:identifier];
    if (!object) {
        object = [MyCoreDataManager newObject];
    }
    return object;
}
@end
```

I will think of a better way to explain this in the docs before I close the issue, but does this help you for now?

**Comment by SPopenko** [comment]
@LoganWright thanks! it totally makes sense.

**Comment by LoganWright** [comment]
This has been updated with a brief explanation in the new version.

**Comment by SPopenko** [comment]
@LoganWright great! thank you.

**Comment by dslysenko** [comment]
Any way to do this in Swift? I keep getting a "Cannot convert return expression of type 'SocialAccount' to type 'Self'" on a managed object subclass. I'm not sure that the type inference is possible in Swift, but if anyone knows, you will. Is CustomMappable maybe only available on structs?

**Comment by LoganWright** [comment]
Hi @dslysenko 

This is totally possible in Swift, but we have to get a tiny bit tricky w/ core data.  My guess is that you have something like this:

```Swift
    static func newInstance(map: Map) -> Self {
        return SocialAccount(entity: NSEntityDescription(), insertIntoManagedObjectContext: nil)
    }
```

This will fail because it initializes a `SocialAccount` object and not whatever `Self` is.  To work with `self` without a `final` class, we have to use `self.init`:


```Swift
    static func newInstance(map: Map) -> Self {
        return self.init(entity: NSEntityDescription(), insertIntoManagedObjectContext: nil)
    }
```

But then, we need to make the initializer required so we can guarantee all inherited classes also conform.  So our final implementation might look something like this:

```Swift
class SocialAccount : NSManagedObject, CustomMappable {
    static func newInstance(map: Map) -> Self {
        return self.init(entity: NSEntityDescription(), insertIntoManagedObjectContext: nil)
    }
    
    required override init(entity: NSEntityDescription, insertIntoManagedObjectContext managedObjectContext: NSManagedObjectContext?) {
        super.init(entity: entity, insertIntoManagedObjectContext: managedObjectContext)
    }
    
    func sequence(map: Map) throws {
    }
}
```

It might be a good idea to setup a base class for your models and inherit from that so you don't have to repeat your code everywhere.

Does this help at all?

**Comment by dslysenko** [comment]
Interesting and thanks for the quick response! I sorta got around it quickly by overriding initializer() like so:

```static func initializer() -> MappableCoreDataInitializer {
        return findOrCreateInstance
    }
    
    private static func findOrCreateInstance(map: Map) throws -> MappableObject {
      // code
    }```

This is a great project and I love the idea! Unfortunately I don't think I can use it in my current app because I make heavy use of private contexts and SwiftyJSON (built into my custom-made networking lib).

Since that comment I also actually ended up writing a new protocol that supports a private context in mapping, but I did not get a chance to test it as I got a different idea for how to propagate JSON errors with minimal effect on our current workflow -- inspired by this project of course ;)

**Comment by LoganWright** [comment]
@dslysenko 

That seems like a fine initializer, that's the whole reason why I created it that way, so that anyone could define an initializer that suits their situation!

The provided protocols with initializers are just an easy way for people to adapt if they're new to the way protocols interact in Swift.

I'd love this project to offer a wide range of support, so if you find something that isn't supported, and could be easily added as an opt in feature, definitely let me know and I'll see if I can integrate it.

Thanks for checking out the lib and let me know if you keep working on it!

- Logan

**Comment by dslysenko** [comment]
@LoganWright Not sure if this qualifies as "could be easily added as an opt in feature" as it would probably require some extra thought as to architecture beyond what I've put in (I'm not really satisfied with the new protocol so I imagine you wouldn't be), but here's what I came up with to solve the context problem:

https://gist.github.com/dslysenko/ebc5092e85f5727eafa4

**Comment by LoganWright** [comment]
@dslysenko 

Sorry about the late reply, I missed the alert about this message. I actually think what you have seems like a pretty good workaround for the NSManagedContext issue, but it will definitely cause opt in problems.

One goal of this library is to be prepared for cross platform support which generally means any `NS` class can't be included by default.  I'm going to think about this longer, but I'm toying with the idea of making a `Genome+CoreData` podspec that basically appends this to the Genome core. 

For the interim, I'm going to post your relevant snippet here in case other people stumble this way:

```Swift
// MARK: Genome+MappableCoreDataObject
typealias MappableCoreDataInitializer = (map: Map, context: NSManagedObjectContext) throws -> MappableObject
protocol MappableCoreDataObject: MappableObject {
    static func initializer() -> MappableCoreDataInitializer
}
extension MappableCoreDataObject {
    static func initializer() -> Initializer {
        // return try initializer(context: NSManagedObjectContext.MR_defaultContext())
        fatalError("no soup for you")
        // Not sure how to resolve this 
    }
    
    static func mappedInstance(js: Genome.JSON, context: NSManagedObjectContext) throws -> Self {
        let map = Map(json: js, context: [:])
        let initialization = initializer() // auto maps to the MappableCoreDataInitializer()
        var instance = try initialization(map: map, context: context)
        assert(instance is Self,
            "Unfortunately, in order to support flexible subclassing, while also not enforcing a specific initializer, I need to be lenient with my type specifications in MappableObject protocol.  Otherwise, an error is thrown 'You are unable to 'use Self in a non-parameter, non-result type position`.  This means that although `Initializer` is of type `Map -> MappableObject`, it should really be considered `Map -> Self`!"
        )
        try instance.sequence(map)
        return instance as! Self
    }
}
```

**Comment by LoganWright** [comment]
```Swift
typealias MappableCoreDataInitializer = (map: Map, context: NSManagedObjectContext) throws -> MappableObject
protocol MappableCoreDataObject: MappableObject {
    static func initializer() -> MappableCoreDataInitializer
    static func findOrCreateInstance(map: Map, context: NSManagedObjectContext) throws -> MappableObject
}
extension MappableCoreDataObject {
    static func initializer() -> Initializer {
        return findOrCreateInstance
    }
    
    static func mappedInstance(js: Genome.JSON, context: NSManagedObjectContext) throws -> Self {
        let map = Map(json: js, context: [:])
        let initialization = initializer() // auto maps to the MappableCoreDataInitializer()
        var instance = try initialization(map: map, context: context)
        assert(instance is Self,
            "Unfortunately, in order to support flexible subclassing, while also not enforcing a specific initializer, I need to be lenient with my type specifications in MappableObject protocol.  Otherwise, an error is thrown 'You are unable to 'use Self in a non-parameter, non-result type position`.  This means that although `Initializer` is of type `Map -> MappableObject`, it should really be considered `Map -> Self`!"
        )
        try instance.sequence(map)
        return instance as! Self
    }
}
```

**Comment by LoganWright** [comment]
@dslysenko 

I think I've come up with what I consider to be a valuable alternative.  Here's the final result:

```Swift
protocol CoreDataMappable: MappableObject {
    static func newInstance(map: Map, context: NSManagedObjectContext) throws -> Self
}

extension CoreDataMappable {
    static func initializer() -> Initializer {
        fatalError("Core data objects must be initialized with `mappedInstance(js: JSON, contect: NSManagedObjectContext!")
    }
    
    static func mappedInstance(js: JSON, context: NSManagedObjectContext) throws -> Self {
        let map = Map(json: js, context: [:])
        var instance = try newInstance(map, context: context)
        try instance.sequence(map)
        return instance
    }
}

extension Array where Element : CoreDataMappable {
    static func mappedInstance(js: [JSON], context: NSManagedObjectContext) throws -> Array {
        return try js.map { try Element.mappedInstance($0, context: context) }
    }
}
```

We don't actually need the special initializer, or the assertion here because we can be a little less flexible.  This initialization is for CoreData objects and we can make some exceptions.  I think this is a good starting point, and people can modify their own.

Unfortunately, this won't support nested objects, so there's still work to do on my end.  I guess I hadn't considered multiple contexts when originally designing this.  It may end up not being fully supported, but we'll see where it ends up.
