### ISSUE TITLE
Can't build with Carthage

### ISSUE THREAD

**Issue by rizumita** [LoganWright/Genome#60]
I tried building Genome 3.0.0 with Carthage, but I couldn't build with error 'Dependency "Genome" has no shared framework schemes for any of the platforms: iOS'.

**Comment by rizumita** [comment]
Would you append a binary to release for carthage?

**Comment by LoganWright** [comment]
@rizumita 3.0.0 is tagged so that SPM can be used, but isn't really ready for production yet. It's built on Swift 3 and usually sticks to the latest snapshot. You won't be able to submit to app store or use w/ default toolchain in Xcode.

If you're still interested, I can look into what it would take to make the lib play nice w/ Carthage in its current state 👍

**Comment by rizumita** [comment]
@LoganWright I see. Then must I use ver.2.0.4?

**Comment by LoganWright** [comment]
@rizumita For now, 2.0.4 is the latest! 3.0 is close, needs some updated tests and then just waiting for some official releases.

**Comment by LoganWright** [comment]
Moving to #65
